DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/MMSFormer'          # output folder name used for saving the model, logs and inference results
#GPUs            : 2
#GPU_IDs         : [0, 1]
GPUs            : 1
GPU_IDs         : [0]
USE_WANDB       : false
WANDB_NAME      : 'MMSF-MORTARS-CONFIG'             # name for the run

MODEL:
  NAME          : MMSFormer                                         # name of the model you are using
  BACKBONE      : MMSFormer-B3                                      # model variant
  PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b3.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : MORTARS                                               # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/home/leonardonotari/elabIVA/mortars_dataset'                            # dataset root path
  IGNORE_LABEL  : 3
  # MODALS        : ['img']
  MODALS        : ['paralleli', 'incrociati'] 

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 4            # batch size used to train
  EPOCHS        : 1           # number of epochs to train
  EVAL_START    : 0              # evaluation interval during training
  EVAL_INTERVAL : 1              # evaluation interval during training
  AMP           : true            # use AMP in training
  DDP           : false           # use DDP training
  WEIGHTED_RANDOM_SAMPLER : false

LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation
  CLASS_WEIGHTS : [1.0, 8.0, 2.5] 

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0001         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.005            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'output/MMSFormer/MMSF-MORTARS-CONFIG/MMSFormer_MMSFormer-B3_MORTARS_epoch1_49.64.pth'                  # Path to your saved model
  IMAGE_SIZE    : [512, 512]                              # evaluation image size in (h, w)                       
  BATCH_SIZE    : 1                                     # batch size
  SAVE_PREDICTIONS : true
  ERROR_THRESHOLD: 0.15
  SAVE_CONFUSION: True
  VIS_SAVE_DIR  : 'data/mortars_results'                      # Where to save visualization
  CONFUSION_DIR : 'data/confusion_matrix'
  MSF:  
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
